title: Finding Paths
description: >
  **Jasper van Wanrooy**,
  principal engineer @ Coolblue,
  Automation, AWS, Databases, Docker, Hiking, PHP, Python, Reliability, Sailing

copyright: "Jasper van Wanrooy"
baseurl:
url: https://findingpaths.io

disqus_shortname: "finding-paths"

analytics:
  google_analytics_code: "UA-104466527-1"

contact:
  email: "jasper@vanwanrooy.net"
  facebook:
  twitter: "jappievw"
  linkedin: "jaspervanwanrooy"
  github:  "jappievw"

feed_icon: rss

permalink: /:title
paginate_path: "/page/:num/"
paginate: 5

gems:
  - jekyll-paginate
exclude:
  - docker-compose.yml
  - CODEOWNERS
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
